---
- hosts: shashank
  remote_user: shashank
  become: true
  roles:
      - { role: ansible-role-nginx,         tags: [ 'ansible-role-nginx'      ]}
      # - { role: deploy-changelly,         tags: [ 'deploy-code' ]}
